import type { LocalPost } from './types'

export const meeshoSkuId: LocalPost = {
  slug: 'meesho-sku-id-explained',
  title: 'What the SKU ID on a Meesho label actually means, and how to name it',
  excerpt:
    'Your label shows a SKU ID, not a product name. Here is where that string comes from, why one product often has several, and how to set up naming so packing gets easier.',
  publishedAt: '2026-08-24',
  readingMinutes: 5,
  category: 'Catalogue',
  author: 'Akshit Ahuja',
  keywords: [
    'meesho sku id',
    'meesho sku meaning',
    'meesho product mapping',
    'meesho catalogue sku',
  ],
  html: `
<p>Look at any Meesho shipping label and you will find a small table near the middle: SKU, Size, Qty, Color, Order No. The SKU column holds a string like <code>2pc_COMB0_LEGEND</code> or <code>765_REDCOLOR_LIONPRINT</code>. That string is doing more work than most sellers realise, and understanding it makes a real difference to how fast you can pack.</p>

<h2>Where the SKU ID comes from</h2>

<p>The SKU ID is not generated by Meesho. It is the identifier <em>you</em> supplied when you uploaded the catalogue. Whatever you typed into the SKU field in the catalogue upload sheet is what ends up printed on every label for that variant, forever.</p>

<p>That has one immediate consequence: the SKU ID is only as readable as the day you were in a hurry uploading a hundred products. If you typed <code>t1</code>, <code>t2</code>, <code>t3</code> at 11pm, your labels now say <code>t1</code>, <code>t2</code>, <code>t3</code>.</p>

<h2>Why one product often has several SKU IDs</h2>

<p>This is the part that catches people out. A single thing you think of as "one product" can easily carry three or four different SKU IDs:</p>

<ul>
  <li><strong>Re-uploads.</strong> You listed the product, it did not sell, you relisted it with a fresh catalogue and a new SKU. Both catalogues are still live.</li>
  <li><strong>Colour or pack variants.</strong> The same design in black and in white can be two catalogues with two SKU roots.</li>
  <li><strong>Price experiments.</strong> Sellers often duplicate a catalogue to test a different price point, and the duplicate gets its own SKU.</li>
  <li><strong>Typos.</strong> <code>LEGEND_BLK</code> and <code>LEGEND-BLK</code> are two different SKUs to a computer, even though they are one product to you.</li>
</ul>

<p>The result is that your shelf has one box, and your labels have four different names for it. That is precisely the mismatch that makes automated sorting look wrong when it is actually correct.</p>

<h2>The fix: map SKU IDs to a name you use</h2>

<p>The practical solution is a mapping. On one side, the product name your packing table uses. On the other, every Meesho SKU ID that means that product.</p>

<pre><code>LEGEND COMBO BLACK  →  2pc_COMB0_LEGEND
                       2pc-COMBO-LEGEND
                       LEGEND_BLK_2PC</code></pre>

<p>Once that mapping exists, a sorting tool can group all three SKU IDs into a single pile and print <strong>LEGEND COMBO BLACK</strong> on all of them. Your team never sees the SKU string again.</p>

<p>The rule that keeps this sane is one-way: a product can own many SKU IDs, but a SKU ID belongs to exactly one product. If you try to put the same SKU under two products, one of them has to give it up, otherwise the tool has no way to decide which name to print.</p>

<h2>Do it once, from a real file</h2>

<p>You do not need to type SKU IDs out of your catalogue. The faster route is to let a tool read one of your existing label PDFs, pull out every SKU ID it finds, and then hand you that list to name. Ten minutes on a busy day's file will usually cover ninety percent of what you ship.</p>

<p>New SKUs appear over time, of course. When one shows up, the tool flags it rather than guessing, prints the raw SKU ID on those labels, and keeps them at the end of the pile so they are easy to spot and name later.</p>

<h2>Naming SKUs better going forward</h2>

<p>For anything you upload from here on, a small amount of discipline pays off:</p>

<ul>
  <li>Put the product first, then the variant: <code>LEGENDCOMBO-BLACK-M</code> beats <code>M-BLACK-2pc</code>.</li>
  <li>Pick one separator and stick to it. Mixing <code>_</code> and <code>-</code> creates duplicates that look identical to you.</li>
  <li>Avoid ambiguous shorthand. <code>BLK</code> today is a mystery in eight months.</li>
  <li>Never reuse a retired SKU for a different product. Old returns and old labels will come back to confuse you.</li>
</ul>

<p>None of this is glamorous, but a readable SKU is the difference between a packing table that runs itself and one that needs you standing next to it.</p>

<p>If you want the mapping set up for you, <a href="/tools/meesho-label-sorter/">the Label Sorter</a> collects the SKU IDs from your own label PDF and lets you name them in one screen.</p>
`,
}
