import type { Article } from './types'

export const meeshoSkuId: Article = {
  slug: 'meesho-sku-id-explained',
  title: 'Meesho SKU ID explained, and why one product often has several',
  seoTitle: 'Meesho SKU ID: What It Means and How to Name Yours Properly',
  excerpt:
    'Your label shows a SKU ID, not a product name. Here is where that string comes from, why the same product ends up with three or four of them, and how to map them so packing stops being guesswork.',
  seoDescription:
    'What the SKU ID on a Meesho label actually means, why one product has several, and how to map them to readable product names. Guide for Meesho sellers.',
  publishedAt: '2026-08-24',
  readingMinutes: 6,
  category: 'Catalogue',
  author: 'Akshit Ahuja',
  keywords: [
    'meesho sku id',
    'meesho sku meaning',
    'what is sku id in meesho',
    'meesho product mapping',
    'meesho catalogue sku',
    'sku naming convention',
  ],
  answer:
    'A Meesho SKU ID is the product code you entered when uploading your catalogue, printed on every shipping label for that variant. Meesho does not generate it. One product often carries several SKU IDs because of relists, colour variants and price tests.',
  faqs: [
    {
      question: 'What does SKU stand for?',
      answer:
        'Stock Keeping Unit. It is a general retail term for the code identifying one specific sellable variant, meaning a particular product in a particular size and colour, so that inventory can be counted accurately across listings and warehouses.',
    },
    {
      question: 'Can I change a SKU ID on a live Meesho catalogue?',
      answer:
        'Changing a SKU on a catalogue that already has orders is risky, because open orders, returns and printed labels still reference the old value. It is usually safer to leave existing SKUs alone and apply better naming to new uploads only.',
    },
    {
      question: 'Is the SKU ID the same as the order number?',
      answer:
        'No. The SKU ID identifies the product variant and repeats across every order for that item. The order number is unique to a single order. Both print on a Meesho shipping label, in different columns of the same product table.',
    },
    {
      question: 'Why does my label show a SKU I do not recognise?',
      answer:
        'Usually an old relisted catalogue that is still live and still taking orders. Search that exact string in your supplier panel catalogue list and you will find which listing it belongs to.',
    },
    {
      question: 'Can two products share one SKU ID?',
      answer:
        'No, and no tool should let you map it that way. A product can own many SKU IDs, but a SKU ID must belong to exactly one product, otherwise software has no way to decide which product name to print on the label.',
    },
  ],
  html: `
<div class="tldr">
  <p>Key takeaways</p>
  <ul>
    <li>The SKU ID on a Meesho label is the identifier <em>you</em> typed when you uploaded the catalogue, not something Meesho generated.</li>
    <li>One product commonly carries three or four SKU IDs because of relists, colour variants, price tests and typos.</li>
    <li>The fix is a mapping: many SKU IDs on one side, one product name you actually use on the other.</li>
    <li>The rule that keeps it sane: a product can own many SKU IDs, but a SKU ID belongs to exactly one product.</li>
    <li>Do not retype your catalogue. Pull the SKU IDs out of a label PDF you already have.</li>
  </ul>
</div>

<p>Look at any Meesho shipping label and you will find a small table near the middle: SKU, Size, Qty, Color, Order No. The SKU column holds a string like <code>2pc_COMB0_LEGEND</code> or <code>765_REDCOLOR_LIONPRINT</code>.</p>

<p>That string is doing more work than most sellers realise, and understanding it is the difference between a packing table that runs itself and one that needs you standing next to it. This guide is for Meesho sellers who are tired of decoding their own SKU IDs at the shelf.</p>

<p><strong>Scope:</strong> this is about reading and organising the SKU IDs you already have. It does not cover catalogue creation, pricing or how Meesho ranks listings. I build the free label tool linked at the end, which is one way to apply the mapping described here, but the naming advice stands on its own.</p>

<div class="toc">
  <p>On this page</p>
  <ol>
    <li><a href="#where-from">Where the SKU ID comes from</a></li>
    <li><a href="#several">Why one product ends up with several</a></li>
    <li><a href="#mapping">The fix: map SKU IDs to a name you use</a></li>
    <li><a href="#once">Do it once, from a file you already have</a></li>
    <li><a href="#naming">Naming SKUs better going forward</a></li>
  </ol>
</div>

<h2 id="where-from">Where the SKU ID comes from</h2>

<p>The SKU ID is not generated by Meesho. It is the identifier you supplied when you uploaded the catalogue. Whatever went into the SKU field of the catalogue upload sheet is what prints on every label for that variant, for as long as the catalogue is live.</p>

<p>That has one immediate consequence. Your SKU IDs are exactly as readable as you were careful on the night you uploaded a hundred products in a hurry. If you typed <code>t1</code>, <code>t2</code>, <code>t3</code> at 11pm, your labels now say <code>t1</code>, <code>t2</code>, <code>t3</code>, and they will keep saying that.</p>

<p>Meesho's own <a href="https://supplier.meesho.com/" target="_blank" rel="noopener noreferrer">supplier panel</a> is where the catalogue and its SKUs are managed, so that is where you check what you actually uploaded.</p>

<h2 id="several">Why one product ends up with several</h2>

<p>This is the part that catches people out. A single thing you think of as one product can easily carry three or four different SKU IDs:</p>

<ul>
  <li><strong>Relists.</strong> You listed the product, it did not sell, you relisted it with a fresh catalogue and a new SKU. Both catalogues are still live and both still take orders.</li>
  <li><strong>Colour or pack variants.</strong> The same design in black and in white can be two catalogues with two SKU roots, even though they come off the same shelf.</li>
  <li><strong>Price experiments.</strong> Duplicating a catalogue to test a different price point is common, and the duplicate gets its own SKU.</li>
  <li><strong>Typos and separators.</strong> <code>LEGEND_BLK</code> and <code>LEGEND-BLK</code> are two different SKUs to a computer and one product to you.</li>
</ul>

<p>The result is that your shelf has one box and your labels have four names for it. That mismatch is exactly why automated sorting can look wrong when it is actually correct: the software grouped by SKU, and you were thinking in products.</p>

<h2 id="mapping">The fix: map SKU IDs to a name you use</h2>

<p>The practical solution is a mapping. On one side, the product name your packing table uses. On the other, every Meesho SKU ID that means that product.</p>

<div class="table-scroll">
<table>
  <thead>
    <tr><th>Your product name</th><th>Meesho SKU IDs it covers</th></tr>
  </thead>
  <tbody>
    <tr>
      <td>LEGEND COMBO BLACK</td>
      <td><code>2pc_COMB0_LEGEND</code><br><code>2pc-COMBO-LEGEND</code><br><code>LEGEND_BLK_2PC</code></td>
    </tr>
    <tr>
      <td>LION PRINT RED</td>
      <td><code>765_REDCOLOR_LIONPRINT</code><br><code>LION_RED_TSHIRT</code></td>
    </tr>
  </tbody>
</table>
</div>

<p>Once that mapping exists, a sorting tool can group all three SKU IDs into a single pile and print <strong>LEGEND COMBO BLACK</strong> on all of them. Your team never sees the SKU string again.</p>

<p>One rule keeps this sane, and it only goes one way: <strong>a product can own many SKU IDs, but a SKU ID belongs to exactly one product.</strong> If you try to put the same SKU under two products, one of them has to give it up, because otherwise the software has no way to decide which name to print. A well-built tool will enforce that for you rather than letting you create the conflict.</p>

<h2 id="once">Do it once, from a file you already have</h2>

<p>You do not need to retype SKU IDs out of your catalogue. The faster route is to let a tool read one of your existing label PDFs, pull out every SKU ID it finds, and hand you that list to name.</p>

<p>Ten minutes spent on a busy day's file usually covers ninety percent of what you ship, because a busy day's file contains your top sellers by definition. The long tail can wait.</p>

<p>New SKUs will appear over time, whenever you list something new. A sensible tool flags those rather than guessing: it prints the raw SKU ID on those labels and keeps them at the end of the pile so they are easy to spot and name later.</p>

<h2 id="naming">Naming SKUs better going forward</h2>

<p>For anything you upload from here on, a small amount of discipline pays off on every future order:</p>

<ul>
  <li><strong>Product first, variant second.</strong> <code>LEGENDCOMBO-BLACK-M</code> beats <code>M-BLACK-2pc</code>, because it sorts and scans in the order you think.</li>
  <li><strong>Pick one separator and stick to it.</strong> Mixing <code>_</code> and <code>-</code> creates near-duplicates that look identical to you and different to software.</li>
  <li><strong>Avoid shorthand you will forget.</strong> <code>BLK</code> is obvious today and a mystery in eight months.</li>
  <li><strong>Never reuse a retired SKU</strong> for a different product. Old returns and old labels come back and will map to the wrong thing.</li>
  <li><strong>Keep it under about 20 characters.</strong> Long SKUs get truncated or wrap awkwardly in the label's table cell.</li>
</ul>

<p>None of this is glamorous. It is also the single cheapest operational improvement available to a small seller, because it costs one evening and pays out on every order forever.</p>

<h2>Next step</h2>

<p>If you want the mapping set up without retyping anything, <a href="/tools/meesho-label-sorter/">the Label Sorter</a> collects every SKU ID from your own label PDF and lets you name them in one screen. From then on your labels print the name instead of the code. It is free and runs in your browser, so nothing is uploaded.</p>
`,
}
